### ISSUE TITLE
Incompatibility with config4k-0.4.1

### ISSUE THREAD

**Issue by lynxpluto** [taymyr/lagom-metrics#9]
Current version of metrics library is built around the `config4k v 0.4.0`. When using it with another library which is `config4k v. 0.4.1` dependent then the error occurs. 
```
[error] 1) Error injecting constructor, java.lang.NoSuchMethodError: org.taymyr.lagom.metrics.Metrics$$special$$inlined$extract$1.genericType()Ljava/util/List;
[error]   at org.taymyr.lagom.metrics.Metrics.<init>(Metrics.kt:45)
[error]   at org.taymyr.lagom.metrics.Metrics.class(Metrics.kt:44)
[error]   while locating org.taymyr.lagom.metrics.Metrics
[error]     for the 2nd parameter of org.taymyr.lagom.metrics.MetricsFilter.<init>(MetricsFilter.kt:26)
[error]   while locating org.taymyr.lagom.metrics.MetricsFilter
```
The `sbt` dependency resolution log output
```
* io.github.config4k:config4k:0.4.1 is selected over 0.4.0
[warn]         +- org.taymyr.lagom:lagom-soap-client-java_2.12:1.0.0 (depends on 0.4.1)
[warn]         +- org.taymyr.lagom:lagom-metrics-java_2.12:1.0.0     (depends on 0.4.0)
```

Version of the `io.github.config4k:config4k` for `lagom-metrics` should also be upgraded to 0.4.1

**Comment by ihostage** [comment]
Good catch 👍
